---

# Tasks file to "install_packages"

 - name: "install_packages: Run apt-get update"
   apt: update_cache=yes

 - name: "install_packages: Install list of packages"
   action: apt pkg={{item}} state=installed
   with_items:
     - build-essential
     - git-core
     - vim
